export const cropData = [
    // --- CEREALS ---
    {
        id: 'jowar',
        name: 'Jwari',
        marathiName: 'ज्वारी',
        englishName: 'Sorghum (Jowar)',
        rank: 1,
        image: 'https://images.unsplash.com/photo-1667662345520-243e0ce7eb56?auto=format&fit=crop&q=80',
        price: '₹3,200/quintal',
        matchScore: 95,
        tags: ['Drought Resistant', 'Staple'],
        profit: '₹30k-45k',
        profitPer: 'per acre',
        suitableSoils: ['black', 'loamy', 'sandy'],
        seasons: ['kharif', 'rabi'],
        soil: ['Black', 'Red'],
        season: ['Kharif', 'Rabi'],
        waterReq: 'Low',
        risks: { weather: { value: 20, level: 'Low' }, market: { value: 30, level: 'Low' }, water: { value: 20, level: 'Low' } },
        calendar: { start: 'Jun', end: 'Oct', duration: '110-120 days' },
        outlook: [{ week: 'W1', icon: 'Sun', status: 'Clear' }, { week: 'W2', icon: 'Sun', status: 'Clear' }, { week: 'W3', icon: 'Sun', status: 'Clear' }, { week: 'W4', icon: 'Cloud', status: 'Cloudy' }]
    },
    {
        id: 'bajra',
        name: 'Bajri',
        marathiName: 'बाजरी',
        englishName: 'Pearl Millet (Bajra)',
        rank: 2,
        image: 'https://images.unsplash.com/photo-1634547970878-5743b013c721?auto=format&fit=crop&q=80',
        price: '₹2,350/quintal',
        matchScore: 90,
        tags: ['Low Water', 'Short Duration'],
        profit: '₹25k-40k',
        profitPer: 'per acre',
        suitableSoils: ['sandy', 'red', 'loamy'],
        seasons: ['kharif', 'summer'],
        soil: ['Sandy', 'Red'],
        season: ['Kharif', 'Summer'],
        waterReq: 'Low',
        risks: { weather: { value: 15, level: 'Low' }, market: { value: 25, level: 'Low' }, water: { value: 10, level: 'Very Low' } },
        calendar: { start: 'Jun', end: 'Sep', duration: '90-100 days' },
        outlook: [{ week: 'W1', icon: 'Sun', status: 'Hot' }, { week: 'W2', icon: 'Sun', status: 'Hot' }, { week: 'W3', icon: 'Sun', status: 'Clear' }, { week: 'W4', icon: 'Cloud', status: 'Cloudy' }]
    },
    {
        id: 'wheat',
        name: 'Gahu',
        marathiName: 'गहू',
        englishName: 'Wheat',
        rank: 3,
        image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&q=80',
        price: '₹2,275/quintal',
        matchScore: 88,
        tags: ['Rabi Staple', 'High Demand'],
        profit: '₹50k-80k',
        profitPer: 'per acre',
        suitableSoils: ['black', 'loamy'],
        seasons: ['rabi'],
        soil: ['Black', 'Alluvial'],
        season: ['Rabi'],
        waterReq: 'Medium',
        risks: { weather: { value: 30, level: 'Medium' }, market: { value: 20, level: 'Low' }, water: { value: 60, level: 'Medium' } },
        calendar: { start: 'Nov', end: 'Mar', duration: '120 days' },
        outlook: [{ week: 'W1', icon: 'Sun', status: 'Cool' }, { week: 'W2', icon: 'Sun', status: 'Clear' }, { week: 'W3', icon: 'Sun', status: 'Clear' }, { week: 'W4', icon: 'Sun', status: 'Clear' }]
    },
    {
        id: 'rice',
        name: 'Tandul',
        marathiName: 'भात / तांदूळ',
        englishName: 'Rice (Paddy)',
        rank: 4,
        image: 'https://images.unsplash.com/photo-1597816766436-b6b80145be8a?auto=format&fit=crop&q=80',
        price: '₹3,100/quintal',
        matchScore: 85,
        tags: ['High Water', 'Konkan Special'],
        profit: '₹40k-70k',
        profitPer: 'per acre',
        suitableSoils: ['loamy', 'red', 'black'],
        seasons: ['kharif', 'summer'],
        soil: ['Loamy', 'Red'],
        season: ['Kharif', 'Summer'],
        waterReq: 'High',
        risks: { weather: { value: 50, level: 'Medium' }, market: { value: 20, level: 'Low' }, water: { value: 90, level: 'High' } },
        calendar: { start: 'Jun', end: 'Oct', duration: '130-140 days' },
        outlook: [{ week: 'W1', icon: 'CloudRain', status: 'Rain' }, { week: 'W2', icon: 'CloudRain', status: 'Rain' }, { week: 'W3', icon: 'Cloud', status: 'Cloudy' }, { week: 'W4', icon: 'Sun', status: 'Clear' }]
    },

    // --- CASH CROPS ---
    {
        id: 'sugarcane',
        name: 'Oos',
        marathiName: 'ऊस',
        englishName: 'Sugarcane',
        rank: 5,
        image: 'https://images.unsplash.com/photo-1601625463687-25541fb72f62?auto=format&fit=crop&q=80',
        price: '₹3,400/ton',
        matchScore: 92,
        tags: ['Cash Crop', 'Long Duration'],
        profit: '₹1.5L-2.5L',
        profitPer: 'per acre',
        suitableSoils: ['black', 'loamy'],
        seasons: ['all_year', 'kharif', 'suru'],
        soil: ['Black', 'Alluvial'],
        season: ['Whole Year'],
        waterReq: 'High',
        risks: { weather: { value: 20, level: 'Low' }, market: { value: 10, level: 'Low' }, water: { value: 100, level: 'Very High' } },
        calendar: { start: 'Jan', end: 'Dec', duration: '12-18 months' },
        outlook: [{ week: 'W1', icon: 'Sun', status: 'Clear' }, { week: 'W2', icon: 'Sun', status: 'Clear' }, { week: 'W3', icon: 'Sun', status: 'Clear' }, { week: 'W4', icon: 'Sun', status: 'Clear' }]
    },
    {
        id: 'cotton',
        name: 'Kapus',
        marathiName: 'कापूस',
        englishName: 'Cotton',
        rank: 6,
        image: 'https://images.unsplash.com/photo-1594498653385-d5172c532c00?auto=format&fit=crop&q=80',
        price: '₹7,200/quintal',
        matchScore: 80,
        tags: ['Black Gold', 'Vidarbha Special'],
        profit: '₹50k-90k',
        profitPer: 'per acre',
        suitableSoils: ['black'],
        seasons: ['kharif'],
        soil: ['Black'],
        season: ['Kharif'],
        waterReq: 'Medium',
        risks: { weather: { value: 60, level: 'Medium' }, market: { value: 40, level: 'Medium' }, water: { value: 40, level: 'Medium' } },
        calendar: { start: 'Jun', end: 'Nov', duration: '150-160 days' },
        outlook: [{ week: 'W1', icon: 'Cloud', status: 'Cloudy' }, { week: 'W2', icon: 'Sun', status: 'Clear' }, { week: 'W3', icon: 'Sun', status: 'Clear' }, { week: 'W4', icon: 'CloudRain', status: 'Rain Alert' }]
    },
    {
        id: 'soybean',
        name: 'Soybean',
        marathiName: 'सोयाबीन',
        englishName: 'Soybean',
        rank: 7,
        image: 'https://images.unsplash.com/photo-1599587405238-6a3f169f4705?auto=format&fit=crop&q=80',
        price: '₹4,800/quintal',
        matchScore: 85,
        tags: ['Fast Return', 'Oilseed'],
        profit: '₹40k-65k',
        profitPer: 'per acre',
        suitableSoils: ['black', 'loamy', 'red'],
        seasons: ['kharif'],
        soil: ['Black', 'Loamy'],
        season: ['Kharif'],
        waterReq: 'Medium',
        risks: { weather: { value: 40, level: 'Medium' }, market: { value: 30, level: 'Low' }, water: { value: 50, level: 'Medium' } },
        calendar: { start: 'Jun', end: 'Sep', duration: '90-100 days' },
        outlook: [{ week: 'W1', icon: 'Cloud', status: 'Cloudy' }, { week: 'W2', icon: 'CloudRain', status: 'Rain' }, { week: 'W3', icon: 'Sun', status: 'Clear' }, { week: 'W4', icon: 'Sun', status: 'Clear' }]
    },

    // --- FRUITS & VEG ---
    {
        id: 'onion',
        name: 'Kanda',
        marathiName: 'कांदा',
        englishName: 'Onion',
        rank: 8,
        image: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&q=80',
        price: '₹2,500/quintal',
        matchScore: 75,
        tags: ['Volatile Market', 'Cash Crop'],
        profit: '₹60k-1.2L',
        profitPer: 'per acre',
        suitableSoils: ['loamy', 'red', 'sandy'],
        seasons: ['rabi', 'kharif', 'late_kharif'],
        soil: ['Loamy', 'Red'],
        season: ['Rabi', 'Kharif'],
        waterReq: 'Medium',
        risks: { weather: { value: 70, level: 'High' }, market: { value: 90, level: 'High' }, water: { value: 60, level: 'Medium' } },
        calendar: { start: 'Dec', end: 'Apr', duration: '120 days' },
        outlook: [{ week: 'W1', icon: 'Sun', status: 'Clear' }, { week: 'W2', icon: 'Sun', status: 'Clear' }, { week: 'W3', icon: 'Sun', status: 'Clear' }, { week: 'W4', icon: 'Sun', status: 'Clear' }]
    },
    {
        id: 'grapes',
        name: 'Draksh',
        marathiName: 'द्राक्षे',
        englishName: 'Grapes',
        rank: 9,
        image: 'https://images.unsplash.com/photo-1537640538965-1756e9e43ea9?auto=format&fit=crop&q=80',
        price: '₹55/kg',
        matchScore: 82,
        tags: ['Export Quality', 'High Investment'],
        profit: '₹3L-5L',
        profitPer: 'per acre',
        suitableSoils: ['loamy', 'black'],
        seasons: ['all_year'], // Perennial
        soil: ['Loamy', 'Black'],
        season: ['Whole Year'],
        waterReq: 'High',
        risks: { weather: { value: 90, level: 'High' }, market: { value: 40, level: 'Medium' }, water: { value: 80, level: 'High' } },
        calendar: { start: 'Oct', end: 'Mar', duration: 'Perennial' },
        outlook: [{ week: 'W1', icon: 'CloudRain', status: 'Rain Risk' }, { week: 'W2', icon: 'Sun', status: 'Clear' }, { week: 'W3', icon: 'Sun', status: 'Clear' }, { week: 'W4', icon: 'Cloud', status: 'Cloudy' }]
    },
    {
        id: 'pomegranate',
        name: 'Dalimb',
        marathiName: 'डाळिंब',
        englishName: 'Pomegranate',
        rank: 10,
        image: 'https://images.unsplash.com/photo-1541336032412-2048a678540d?auto=format&fit=crop&q=80',
        price: '₹80/kg',
        matchScore: 88,
        tags: ['Solapur Special', 'Drought Hardy'],
        profit: '₹2L-4L',
        profitPer: 'per acre',
        suitableSoils: ['sandy', 'loamy', 'red'],
        seasons: ['all_year'], // Perennial
        soil: ['Sandy', 'Loamy'],
        season: ['Whole Year'],
        waterReq: 'Low',
        risks: { weather: { value: 40, level: 'Medium' }, market: { value: 30, level: 'Low' }, water: { value: 30, level: 'Low' } },
        calendar: { start: 'Jun', end: 'Jan', duration: 'Perennial' },
        outlook: [{ week: 'W1', icon: 'Sun', status: 'Clear' }, { week: 'W2', icon: 'Sun', status: 'Clear' }, { week: 'W3', icon: 'Sun', status: 'Clear' }, { week: 'W4', icon: 'Sun', status: 'Clear' }]
    },
    {
        id: 'tur',
        name: 'Tur',
        marathiName: 'तूर',
        englishName: 'Pigeon Pea (Tur)',
        rank: 11,
        image: 'https://images.unsplash.com/photo-1627915998188-468065094251?auto=format&fit=crop&q=80', // Using a generic pulse/field image
        price: '₹8,500/quintal',
        matchScore: 90,
        tags: ['Protein Rich', 'Intercrop'],
        profit: '₹35k-50k',
        profitPer: 'per acre',
        suitableSoils: ['black', 'loamy'],
        seasons: ['kharif'],
        soil: ['Black', 'Loamy'],
        season: ['Kharif'],
        waterReq: 'Low',
        risks: { weather: { value: 30, level: 'Low' }, market: { value: 20, level: 'Low' }, water: { value: 20, level: 'Low' } },
        calendar: { start: 'Jun', end: 'Jan', duration: '180 days' },
        outlook: [{ week: 'W1', icon: 'Sun', status: 'Clear' }, { week: 'W2', icon: 'Sun', status: 'Clear' }, { week: 'W3', icon: 'Sun', status: 'Clear' }, { week: 'W4', icon: 'Sun', status: 'Clear' }]
    }
];